//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBoardController.MessageBoardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageBoardService.IMessageBoardService")]
    public interface IMessageBoardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/InsertNewUser", ReplyAction="http://tempuri.org/IMessageBoardService/InsertNewUserResponse")]
        int InsertNewUser(MessageBoardDTO.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/InsertNewUser", ReplyAction="http://tempuri.org/IMessageBoardService/InsertNewUserResponse")]
        System.Threading.Tasks.Task<int> InsertNewUserAsync(MessageBoardDTO.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/CheckUserAndPassword", ReplyAction="http://tempuri.org/IMessageBoardService/CheckUserAndPasswordResponse")]
        MessageBoardDTO.UserDTO CheckUserAndPassword(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/CheckUserAndPassword", ReplyAction="http://tempuri.org/IMessageBoardService/CheckUserAndPasswordResponse")]
        System.Threading.Tasks.Task<MessageBoardDTO.UserDTO> CheckUserAndPasswordAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/FillUsersGrid", ReplyAction="http://tempuri.org/IMessageBoardService/FillUsersGridResponse")]
        System.Collections.Generic.List<MessageBoardDTO.UserDTO> FillUsersGrid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/FillUsersGrid", ReplyAction="http://tempuri.org/IMessageBoardService/FillUsersGridResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MessageBoardDTO.UserDTO>> FillUsersGridAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/GetUserDetails", ReplyAction="http://tempuri.org/IMessageBoardService/GetUserDetailsResponse")]
        MessageBoardDTO.UserDTO GetUserDetails(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/GetUserDetails", ReplyAction="http://tempuri.org/IMessageBoardService/GetUserDetailsResponse")]
        System.Threading.Tasks.Task<MessageBoardDTO.UserDTO> GetUserDetailsAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/IsAdministrator", ReplyAction="http://tempuri.org/IMessageBoardService/IsAdministratorResponse")]
        bool IsAdministrator(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/IsAdministrator", ReplyAction="http://tempuri.org/IMessageBoardService/IsAdministratorResponse")]
        System.Threading.Tasks.Task<bool> IsAdministratorAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/ChangePassword", ReplyAction="http://tempuri.org/IMessageBoardService/ChangePasswordResponse")]
        void ChangePassword(MessageBoardDTO.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/ChangePassword", ReplyAction="http://tempuri.org/IMessageBoardService/ChangePasswordResponse")]
        System.Threading.Tasks.Task ChangePasswordAsync(MessageBoardDTO.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/UpdateIsActive", ReplyAction="http://tempuri.org/IMessageBoardService/UpdateIsActiveResponse")]
        void UpdateIsActive(System.Collections.Generic.List<MessageBoardDTO.UserDTO> users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/UpdateIsActive", ReplyAction="http://tempuri.org/IMessageBoardService/UpdateIsActiveResponse")]
        System.Threading.Tasks.Task UpdateIsActiveAsync(System.Collections.Generic.List<MessageBoardDTO.UserDTO> users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/AddNewPost", ReplyAction="http://tempuri.org/IMessageBoardService/AddNewPostResponse")]
        void AddNewPost(System.Collections.Generic.List<string> addPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/AddNewPost", ReplyAction="http://tempuri.org/IMessageBoardService/AddNewPostResponse")]
        System.Threading.Tasks.Task AddNewPostAsync(System.Collections.Generic.List<string> addPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/FillPostsGrid", ReplyAction="http://tempuri.org/IMessageBoardService/FillPostsGridResponse")]
        System.Collections.Generic.Dictionary<MessageBoardDTO.PostDTO, System.Nullable<System.DateTime>> FillPostsGrid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBoardService/FillPostsGrid", ReplyAction="http://tempuri.org/IMessageBoardService/FillPostsGridResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<MessageBoardDTO.PostDTO, System.Nullable<System.DateTime>>> FillPostsGridAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageBoardServiceChannel : MessageBoardController.MessageBoardService.IMessageBoardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageBoardServiceClient : System.ServiceModel.ClientBase<MessageBoardController.MessageBoardService.IMessageBoardService>, MessageBoardController.MessageBoardService.IMessageBoardService {
        
        public MessageBoardServiceClient() {
        }
        
        public MessageBoardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageBoardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageBoardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageBoardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertNewUser(MessageBoardDTO.UserDTO user) {
            return base.Channel.InsertNewUser(user);
        }
        
        public System.Threading.Tasks.Task<int> InsertNewUserAsync(MessageBoardDTO.UserDTO user) {
            return base.Channel.InsertNewUserAsync(user);
        }
        
        public MessageBoardDTO.UserDTO CheckUserAndPassword(string username) {
            return base.Channel.CheckUserAndPassword(username);
        }
        
        public System.Threading.Tasks.Task<MessageBoardDTO.UserDTO> CheckUserAndPasswordAsync(string username) {
            return base.Channel.CheckUserAndPasswordAsync(username);
        }
        
        public System.Collections.Generic.List<MessageBoardDTO.UserDTO> FillUsersGrid() {
            return base.Channel.FillUsersGrid();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MessageBoardDTO.UserDTO>> FillUsersGridAsync() {
            return base.Channel.FillUsersGridAsync();
        }
        
        public MessageBoardDTO.UserDTO GetUserDetails(int userID) {
            return base.Channel.GetUserDetails(userID);
        }
        
        public System.Threading.Tasks.Task<MessageBoardDTO.UserDTO> GetUserDetailsAsync(int userID) {
            return base.Channel.GetUserDetailsAsync(userID);
        }
        
        public bool IsAdministrator(string username) {
            return base.Channel.IsAdministrator(username);
        }
        
        public System.Threading.Tasks.Task<bool> IsAdministratorAsync(string username) {
            return base.Channel.IsAdministratorAsync(username);
        }
        
        public void ChangePassword(MessageBoardDTO.UserDTO user) {
            base.Channel.ChangePassword(user);
        }
        
        public System.Threading.Tasks.Task ChangePasswordAsync(MessageBoardDTO.UserDTO user) {
            return base.Channel.ChangePasswordAsync(user);
        }
        
        public void UpdateIsActive(System.Collections.Generic.List<MessageBoardDTO.UserDTO> users) {
            base.Channel.UpdateIsActive(users);
        }
        
        public System.Threading.Tasks.Task UpdateIsActiveAsync(System.Collections.Generic.List<MessageBoardDTO.UserDTO> users) {
            return base.Channel.UpdateIsActiveAsync(users);
        }
        
        public void AddNewPost(System.Collections.Generic.List<string> addPost) {
            base.Channel.AddNewPost(addPost);
        }
        
        public System.Threading.Tasks.Task AddNewPostAsync(System.Collections.Generic.List<string> addPost) {
            return base.Channel.AddNewPostAsync(addPost);
        }
        
        public System.Collections.Generic.Dictionary<MessageBoardDTO.PostDTO, System.Nullable<System.DateTime>> FillPostsGrid() {
            return base.Channel.FillPostsGrid();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<MessageBoardDTO.PostDTO, System.Nullable<System.DateTime>>> FillPostsGridAsync() {
            return base.Channel.FillPostsGridAsync();
        }
    }
}
